- src/HtmlGenerator/HtmlGenerator.csproj
- src/HtmlGenerator/Pass1-Generation/Federation.cs
- src/HtmlGenerator/Program.cs
- src/HtmlGenerator/Utilities/WebProxyAuthenticator.cs
The current version fails to run if the user is behind a proxy which requires authentication. I've added a class which will test if proxy authentication is required. If it detects that auth is required it will request the credentials from the user and apply them to WebRequest.DefaultWebProxy.
> Add support for proxy authentication

- README.md
As I was going through the steps to create the SourceBrowser for my own project, I was having difficulty understanding which physical path should actually be given the "SourceIndexServer". This PR is an attempt to make that a bit clearer to the end-users.
> Make README.md clearer

- src/SourceIndexServer/styles.css
We have some code formatted using tabs, which are defaulting to 8 spaces.  This changes the CSS to specify a tab-size of 4 for pre tags (for browsers that support it).
> Set tab-size for code to 4

- src/Common/Log.cs
- src/Common/Paths.cs
- src/HtmlGenerator/Pass1-Generation/GenerateFromBuildLog.cs
- src/HtmlGenerator/Pass1-Generation/SolutionGenerator.cs
- src/HtmlGenerator/Pass1-Generation/TypeScriptSupport.cs
- src/HtmlGenerator/Program.cs
- src/HtmlGenerator/Utilities/Paths.cs
1. I used a relative path for an output directory, e.g. `/out:_index`.
2. One of the projects I was processing caused an MSBuild error, specifically:
System.InvalidCastException: Unable to cast object of type 'Roxel.BuildTasks.EnsureBindingRedirects' to type 'Microsoft.Build.Framework.ITask'.
at Microsoft.Build.Shared.TaskLoader.CreateTask(LoadedType loadedType, String taskName, String taskLocation, Int32 taskLine, Int32 taskColumn, LogError logError, AppDomainSetup appDomainSetup, Boolean isOutOfProc, AppDomain& taskAppDomain)
3. When `FirstChanceExceptionHandler.HandleFirstChanceException` was called, current directory was set to the directory of the project I was processing (probably by MSBuild)
4. That caused a crash since relative path `_index\Errors.txt` didn't exist under that …
> Fixed crash in FirstChanceExceptionHandler for MSBuild error when using relative output path

- src/HtmlGenerator/HtmlGenerator.csproj
SourceBrowser build fails (on nuget pack) if there are spaces in the full path to HtmlGenerator.csproj.
Added quotes around dynamic paths in the MSBuild call to nuget pack.
> Fixed build error when path to HtmlGenerator.csproj contains spaces

- src/HtmlGenerator/Pass1-Generation/ProjectGenerator.cs
The problem is simple: with the code below, generating website took `11:12`:
```c#
var documents = Project.Documents
.Where(IncludeDocument)
.OrderByDescending(GetDocumentSortOrder);
var tasks = documents.Select(d => Task.Run(() => GenerateDocument(d))).ToArray();
await Task.WhenAll(tasks);
```
I noticed a lot of delays with zero CPU usage during website generation and profiler shows a lot of thread pool threads stuck in sync waits somewhere inside asynchronous file system read API, deep inside Roslyn's document model. I've replaced the code above with simple sequential async code and time reduces down to `7:17`, delays are gone:
```c#
var documents = Project.Documents.Where(IncludeDocument).ToList();
foreach (var document in documents)
{
await GenerateDocument(document);
}
```
Uglifying …
> Solve threading issues with concurrent `GenerateDocument()`

- src/HtmlGenerator/Pass1-Generation/ProjectGenerator.ProjectExplorer.cs
- src/HtmlGenerator/Pass1-Generation/SolutionGenerator.cs
- src/HtmlGenerator/Pass2-Finalization/SolutionFinalizer.cs
- src/HtmlGenerator/Program.cs
- src/HtmlGenerator/Utilities/Markup.cs
- src/SourceIndexServer/scripts.js
Let's try one more time :) I've parametrized `scripts.js`, added solution browser link to the bottom of assembly list and fixed some small issues I've introduced :)
Also, one unrelated thing: I've changed the dates rendering to use invariant culture (my work machine has localized OS, so I noticed output like "Indexed on: января 05").
> New '/assemblylist' switch to emit assembly list instead of solution browser

- src/HtmlGenerator/Utilities/Paths.cs
I have a weird issue when generating site from some of the R# projects: for some reason, sometimes projects have all the `Document`s with the same `TextDocument.Name` value and I was unable to understand where it came from. Equal `Name` breaks site generation, since all the files with the same folder starts sharing the same target file path, producing tons of "File is already used by another process" IO exceptions.
For example, our C# support core project `Psi.CSharp.csproj` has all the documents names equal to `"CSharp"` and our Protobuf definiton file format support project `Psi.Protobuf.csproj` has all the documents with weird `"Impl"` as a name. And there is no a single mention of `Impl` everywhere in `Psi.Protobuf.csproj` or somewhere close.
I guess this may be the `MSBuildWorkspace` …
> Avoid use of `Document.Name` to generate target .html file path

- src/HtmlGenerator/Pass1-Generation/Federation.cs
- src/HtmlGenerator/Pass2-Finalization/SolutionFinalizer.cs
- src/HtmlGenerator/Program.cs
- src/HtmlGenerator/Utilities/Paths.cs
- src/SourceIndexServer/scripts.js
Hi,
this PR contains two (sorry about that) changes:
1.) Adds a "/force" command line option that prevents interactive asking about whether an existing directory should be deleted and just does so. (Useful for build servers, etc. where there is no stdin).
2.) Adds the following options to handle federations:
**/nobuiltinfederations**                 Disables the built-in federations and thus effectively turns the
processing to "offline". Our build servers, for example, don't
have internet access. Of course, links to .NET and Roslyn are
not generated that way.
**/offlinefederation:server=filename**
This mitigates the above, basically you can manually download
the Assemblies.txt file from, say, sourcesof.net and then pass
the following: …
> Offline and no-console support

- src/HtmlGenerator/Pass1-Generation/SolutionGenerator.cs
In some cases (with a large network of project references), loading a project into a workspace can take an inordinate amount of time. Setting this flag (when a build has already taken place) ameliorates this problem.
> Add flag to improve performance

- src/HtmlGenerator/Program.cs
Federation support is currently broken, as it tries to add the federated url to the projects path as well.
With these changes federation works as expected.
Example:
/federation:http://referencesource.microsoft.com
This will now properly link to Microsoft Reference Source.
> Fix federation support

- src/GitGlyph/GitBlameVisitor.cs
- src/GitGlyph/GitSourceBrowserPlugin.cs
- src/MEF/ContextKeys.cs
- src/MEF/ILog.cs
- src/MEF/ISourceBrowserPlugin.cs
- src/MEF/ISourceBrowserPluginMetadata.cs
- src/MEF/ISymbolVisitor.cs
- src/MEF/ITextVisitor.cs
- src/MEF/PluginAggregator.cs
- src/MEF/SymbolVisitorWrapper.cs
Cleanups -- realized I hadn't properly namespaced the contracts library for MEF plugins.
> Fix namespace on MEF project.

- src/GitGlyph/packages.config
- src/HtmlGenerator/Pass1-Generation/DocumentGenerator.cs
- src/HtmlGenerator/packages.config
- src/MEF/packages.config
Things I discovered while working on https://github.com/ddurschlag/BitBucketSourceBrowserPlugin . The git plugin can remain as an example in this repo; having an example is useful, and you probably use git if you use SourceBrowser (though you may want to remove the plugin for performance reasons on very large codebases, as git blame is quite slow). This plugin has no need to live in the same repo, and only makes sense if you use bitbucket.
> Cleanups and fixes

- src/HtmlGenerator/Pass1-Generation/DocumentGenerator.cs
- src/HtmlGenerator/Pass1-Generation/SolutionGenerator.cs
- src/HtmlGenerator/Program.cs
This change adds support for defining server path mappings that identify a file system path prefix that maps to a url path.
This enables the "Server Path" links for github/gitlab repositories and any other hosting scheme that enables links like https://server.com/repo/path/to/file.txt
> Add support for server path prefix mappings

- src/HtmlGenerator/App.config
This change adds binding redirects for the msbuild assemblies that mirror the redirects used for msbuild.exe. This allows custom tasks that were build against different versions to work correctly.
> Add MSBuild assembly binding redirects to app.config

- src/GitGlyph/GitBlameVisitor.cs
- src/HtmlGenerator/HtmlGenerator.csproj
- src/HtmlGenerator/Pass1-Generation/SolutionGenerator.cs
- src/HtmlGenerator/Program.cs
- src/HtmlGenerator/Utilities/FirstChanceExceptionHandler.cs
- src/HtmlGenerator/packages.config
- src/MEF/MEF.csproj
- src/MEF/PluginAggregator.cs
- src/MEF/SourceBrowserPluginWrapper.cs
This PR contains a few improvements (I know, I should have split them -- sorry).
1) The git plugin included by default is quieter.
2) The plugin code exposes a list of modules it has pulled plugins from. In combination with a small, separate nuget package I created for parsing up stack traces, this lets the first chance exception handler ignore all exceptions from plugins.
3) A plugin blacklist is maintained and can be passed in from the command line.
4) Exceptions will NEVER bubble out of plugins -- a thin wrapper is used to re-expose plugin functionality with try/catch/log wrapping. This is also on the quiet side of logging.
Further improvements may be possible, but this should be a good start.
> Merge plugin improvements

- README.md
This adds the [unofficial](https://github.com/aspnet/Home/issues/1944#issuecomment-284155872)  version of ASP.NET Core 1.0 source browser to the list.
I can imagine you don't want an unofficial version of the source browser to be added here, and won't accept this PR. Though, for discoverability, this might be very useful, until an official version of ASP.NET Core is available.
> Add ASP.NET Core 1.0 unofficial source browser

- NuGet.config
- src/HtmlGenerator/HtmlGenerator.csproj
- src/HtmlGenerator/Pass1-Generation/MetadataAsSource.cs
- src/HtmlGenerator/Pass1-Generation/SolutionGenerator.cs
- src/HtmlGenerator/Utilities/FirstChanceExceptionHandler.cs
- src/HtmlGenerator/Utilities/WorkspaceHacks.cs
Fixes https://github.com/KirillOsenkov/SourceBrowser/issues/84
This PR updates SourceBrowser to the latest Roslyn beta packages, which includes the `MSBuildWorkspace` update that adds support for multi-targeted projects. Note that this only enables processing of multi-targeted projects. Because SourceBrowser uses "assembly name" as part of path that it generates a project to, only a single target framework actually gets generated. Other target frameworks are skipped.
Proper handling of multi-targeted projects as part of SourceBrowser is a larger effort that will involve re-thinking of how project indices are laid out on disk and how links are generated to navigate between them.
> Update MSBuildWorkspace to enable multi-targeted projects

- src/SourceIndexServer/wwwroot/scripts.js
A file's URL should only contain a comma if it directly precedes a
line number. In the case where a file's name actually contains a
comma, it should be encoded as %2C so the URL can still be split on
comma. This change prevents the encoded comma from being decoded
prematurely, resulting in an incorrect `potentialFile`. Furthermore,
it's completely unnecessary as `decodeURIComponent` on line 104 will
handle the decoding.
> Fix loading files with commas in the name

- src/SourceIndexServer/wwwroot/scripts.js
The "anchorSplitChar" is used to separate the elements of the URL between the filename, the hash or line number if present, and the type of search (namespaces, references, or neither) if present. Currently this character is the comma. Unfortunately comma is a permissible character in filenames as well; in fact, a comma exists in a filename in the test solution (https://github.com/KirillOsenkov/SourceBrowser/blob/master/TestCode/Project2/-._%7E!%24'()%2B%2C%3D%40.cs), so splitting on comma alone is not safe as it results in "filenames" that are missing any text after the comma.
Three solutions come to mind:
- Change the split character to something else, for example a URL-safe character that is not usually allowed in filenames, like `*`. This would require finding all the relevant places …
> scripts.js: handle filenames with commas

- src/HtmlGenerator/Pass1-Generation/SolutionGenerator.cs
Works around exceptions from MSBuildProjectLoader.Worker.LoadProjectInfosFromPathAsync adding the same key multiple times to a dictionary.
> Treat .depproj as .csproj

- src/BuildLogParser/BuildLogParser.csproj
- add netstandard2.0 for BuildLogParser.csproj
- remove the reference for `Microsoft.Build`, because this has been referenced by `Common`
> add netstandard2.0 for BuildLogParser.csproj

- src/Common/Common.csproj
- src/Common/Log.cs
- src/HtmlGenerator/Program.cs
fix #122 
On test solution, here a dottrace snapshot:
we can see lock contention because own time is 54%.
With this PR, this method is reduce to 0 ms.
> Log in an another thread to remove lock contention.

- src/SourceIndexServer/wwwroot/scripts.js
Creating and inserting the img elements under folders in the DOM is slow. For a solution with many projects, the initialization done in makeFoldersCollapsible can take many seconds, or even minutes. This means that when loading the page, there is a long initial period where the page appears unresponsive.
This change addresses that problem by changing makeFoldersCollapsible so that it only initializes the top-level folders, which are initially collapsed. Only when a folder is expanded, do we initialize the contained folder items.
> Defer init of nested solution browser folders until expand

- src/SourceIndexServer/wwwroot/scripts.js
My previous optimization to defer adding folder images was missing support for the Project Explorer and Namespace Explorer (it only worked for Solution Explorer). This change does two things:
1. Ensures that top-level items in the Project/Namespace explorers get proper images upon initial display
2. Ensures that expanding an item for the first time adds images to contained, child folders, even if the item's `initialize` attribute is unset
> Fix tree expansion for Project Explorer and Namespace Explorer

- src/SourceIndexServer/Models/Serialization.cs
There was a recent change to make Source Browser more resilient to individual files being missing. It seems there was a copy-paste error where File.Exists was being called on a directory, rather than the Projects.txt file. This seems to break index loading, because an empty project array is returned.
> Test file existence of the Projects file rather than the folder

- .editorconfig
- README.md
- SourceBrowser.sln
- src/GitGlyph/GitBlameVisitor.cs
- src/HtmlGenerator/Program.cs
- src/HtmlGenerator/Utilities/Paths.cs
- src/HtmlGenerator/Utilities/PluginLogger.cs
Closes #159
Passing `/root:"C:\Users\Joseph\Source\Repos"`:
As a test, passing `/root:"C:\Users\Joseph\Source"`:
> Add option to preserve relative folder structure between .sln files

- src/SourceIndexServer/wwwroot/scripts.js
- src/SourceIndexServer/wwwroot/styles.css
Fixes #163. In the refactoring commit, I aligned the icons to the same pixels by switching between 'before' and 'after' tabs and verifying that the icons didn't move. I made sure everything looked good in Firefox, Chrome, and Edge on Windows 10.
Before/after:
Before:
After:
Before:
After:
> Dark mode arrows

- src/SourceIndexServer/Startup.cs
Fixes #171. Right pane is no longer blank and logging a 404 in the browser console when the filename starting with `.` is clicked:
> Fix blank page for source filenames starting with '.'

- src/HtmlGenerator/Program.cs
Regressed in https://github.com/KirillOsenkov/SourceBrowser/pull/168
> Fix a typo that caused exit showing usage if /p was not used

- src/HtmlGenerator/Pass1-Generation/DocumentGenerator.cs
- src/HtmlGenerator/Pass1-Generation/GenerateFromBuildLog.cs
- src/HtmlGenerator/Pass1-Generation/ProjectGenerator.cs
- src/HtmlGenerator/Pass1-Generation/SolutionGenerator.cs
- src/HtmlGenerator/Pass1-Generation/TypeScriptSupport.cs
- src/HtmlGenerator/Pass1-Generation/XmlSupport.cs
- src/HtmlGenerator/Utilities/Markup.cs
Closes #170
Example:
I thought about unifying the links when the file path is the same as the project path, but the links do different things and it seems better to keep that.
TypeScript support required changes that were more extensive than I felt comfortable doing without testing, but it should be easier to do that part now if anyone wants to.
> Enable 'Web Access' link for XML files

- src/HtmlGenerator/Pass1-Generation/ProjectGenerator.cs
Closes #169
File with `obj` path segment:
File without `obj` path segment:
> Omit 'Web Access' link for files untracked by most gitignores

- src/SourceIndexServer/wwwroot/styles.css
Before:
After:
Ref: https://source.dot.net/#System.Linq/System/Linq/ToCollection.cs,c7f3fa13329a79cd,references
A quick fix for something I noticed a lot that made some of the text less readable when doing horizontal scrolling when there are lots of references.
Note that this means the titles won't wrap anymore, which I think is totally fine. But if that's important I can think of a couple of ways to work around it if needed. What do you think?
> Fix background hidden overflow problem in sidebar with horizontal scroll

- src/SourceIndexServer/wwwroot/styles.css
Before:
After:
This is an extremely straightforward fix in CSS. When you wanna go flex, you usually want to go flex all the way, but in the bg PR I wanted to change the least amount of CSS I could. In any case, this should work as expected now.
As you can see this also fixes a problem in the header caused by #201 too (at the time didn't realize the same styles were being applied to the header too).
Do note though that I wasn't able to test this one locally because of problems generating the test solution (since it uses .net 4.5 and apparently I don't have the dev pack for it), so you might want to do a quick run to make sure it works fine.
Resolves #209
> Make body stretch to flex parent

- .gitignore
- src/HtmlGenerator/HtmlGenerator.csproj
- src/HtmlGenerator/Utilities/WorkspaceHacks.cs
This PR updates Roslyn to v4.4.0.
I was getting the following error with the .NET 7 SDK:
```
Unhandled Exception: System.MissingMethodException: Method not found: 'Void Microsoft.NET.StringTools.SpanBasedStringBuilder.Append(System.ReadOnlyMemory`1<Char>)'.
at Microsoft.Build.Evaluation.Expander`2.SpanBasedConcatenator.Add(ReadOnlyMemory`1 span)
at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveTypedAndEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties, IFileSystem fileSystem, LoggingContext loggingContext)
at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveEscaped(String expression, IPropertyProvider`1 …
```
> Update Roslyn to v4.4.0

- src/SourceIndexServer/Controllers/OpenSearchController.cs
- src/SourceIndexServer/wwwroot/index.html
This is a feature I think all websites with an essential search function should have. "Tab to Search" lets users type the shortcut, usually the domain name, of a web page then press `TAB` and write a query to instantly search on that page.
I have tested this on Microsoft Edge, Firefox, and Google Chrome. Edge instantly activates discovered search engines, while [Firefox](https://support.mozilla.org/en-US/kb/add-or-remove-search-engine-firefox#w_add-search-engines) and [Chrome](https://support.google.com/chrome/answer/95426#edit) requires manual activation.
I have implemented the Open Search Description Document as an API controller. It will return the XML formatted document with the correct content type. The URL base in the document is based on the request URL, this should allow the …
> Add Open Search Description Document to enable "Tab to Search"

- src/HtmlGenerator/Utilities/Paths.cs
Using the Document.Name is the [correct](https://github.com/dotnet/roslyn/issues/12176#issuecomment-265302328) thing to use here, as long as the `<Link>` value is set properly. But an early [commit](https://github.com/KirillOsenkov/SourceBrowser/pull/34) to this repo modified it to use the filename part of Document.FilePath instead, to avoid "File is already used by another process" IO exceptions, which were happening because `<Link>` was not set properly in the project file.
However, with .NET Core .csproj files, sometimes using Document.FilePath can cause the same sort of IO exceptions. In particular, if you have multiple Properties\AssemblyInfo*.cs files, all of them will have the same FilePath value, but the Name value will be the actual filename.
So to fix .NET Core projects like …
> Do not use FilePath if multiple documents share it

- .vscode/settings.json
- src/Common/Common.csproj
- src/HtmlGenerator.Tests/HtmlGenerator.Tests.csproj
- src/HtmlGenerator/HtmlGenerator.csproj
- src/HtmlGenerator/Pass1-Generation/Classifier.cs
- src/HtmlGenerator/Pass1-Generation/DocumentGenerator.HighlightReferences.cs
- src/HtmlGenerator/Pass1-Generation/DocumentGenerator.Links.cs
- src/HtmlGenerator/Pass1-Generation/DocumentGenerator.References.cs
- src/HtmlGenerator/Pass1-Generation/DocumentGenerator.cs
- src/HtmlGenerator/Pass1-Generation/MetadataAsSource.cs
- src/HtmlGenerator/Pass1-Generation/ProjectGenerator.cs
- src/HtmlGenerator/Pass1-Generation/SolutionGenerator.cs
This clean up all the warnings I saw during build. This PR has three commits, one for each category of warnings that I found: 
- NU1701: there are several packages that don't have `netstandard2.0` equivalents that generate warnings. An alternative fix here would be, at least for `Microsoft.Build`, to upgrade to newer packages but that would potentially impact consumers that wanted to keep using 16.8 (not sure how important that is). 
- Roslyn symbol equality: just fixed these by using `SymbolEqualityComparer.Default` 
- VS Threading: this was more complicated. 
- naming rules: this was simple enough so just followed the rules 
- synchronous blocking: this was tough. In a number of places there were fairly obvious code changes (like use `await x` instead of `x.GetAwaiter().GetResult()`. In …
> Clean up build warnings

- TestCode/Project2/Class1.cs
- TestCode/TestSolution_EdgeDriver_Tests/TestSolution_EdgeDriver_Tests.csproj
- src/HtmlGenerator/HtmlGenerator.csproj
This updates Roslyn to v4.8.0.
C# 12 stuff seems to work fine with no other changes, so this PR is straightforward. I upgraded the EdgeDriver test project target framework because of a security vulnerability that generated an error message.
> Update Roslyn to v4.8.0

- TestCode/Project2/Class1.cs
- src/HtmlGenerator/HtmlGenerator.csproj
- src/HtmlGenerator/app.config
I noticed that generic arguments were not bound when `where T : allows ref struct` was specified.
> Update Roslyn to v4.12.0

- src/HtmlGenerator/SourceBrowser.nuspec
Sorry I didn't notice this before I made my previous PR, but apparently the previous Roslyn version shipped a single BuildHost (the `Microsoft.CodeAnalysis.Workspaces.MSBuild.BuildHost.exe` file along with its dependencies), whereas the new version of the `Microsoft.CodeAnalysis.Workspaces.MSBuild` package ships two of those in the `BuildHost-net472` and `BuildHost-netcore` subdirectories, and those were missing in the SourceBrowser package.
Note that I didn't include the BuildHost language resource files since the CodeAnalysis ones were already omitted.
> Fix missing BuildHost
